services:
  db:
    image: postgres:16-alpine
    container_name: marqi_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: marqi_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Newmarqi
    ports:
      - "5437:5432"   # Externo:Interno → accedes en localhost:5437
    volumes:
      - marqi_pgdata:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./db/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d marqi_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  marqi_pgdata:
    driver: local
